config/routes.rb
Rails.application.routes.draw do


  get 'flow/index'

  get 'hello_world', to: 'hello_world#index'
  resources :customers
  get 'notification/view'

  mount Crono::Web, at: '/crono'


  root "home#index"

  get 'subscription/new'

  get 'subscription/subscription_checkout'

  post 'subscription/webhook'

  get 'home/index'

  post 'subscription/subscription_checkout'
  get 'subscription/cancel_subscription'
  get 'subscription/plans'


  resources :profiles
  get 'service_test/index'

  resources :zones

  get 'my_interaction/index'
  get 'my_interaction/new'
  post 'my_interaction/create'

  resources :interactions

  devise_for :users,
               controllers: { registrations: "registrations" }

  get 'my_listing/index'

  resources :searches
  resources :listings
  get 'porta_portese/index'
  get 'porta_portese/run_search'

  get 'results' , to: 'listings#view'

namespace 'api' do
  get 'listing_for_search', to: 'listings#getListingForSearch'
  get 'togglefav', to: 'listings#togglefav'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  default_scope {where(user_id: Current.user.id)}
  belongs_to :user

end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  belongs_to :customer
  default_scope {where(user_id: Current.user.id)}
  accepts_nested_attributes_for :customer

end

app/models/listing.rb
class Listing < ApplicationRecord
  acts_as_votable
  has_many :search_results
  has_many :searches, through: :search_results
  has_many :interactions
  belongs_to :user
  belongs_to :zone

  def pricemq
    p=0
    if self.price != nil && self.mt != nil && self.price != ""  && self.mt != "" && self.mt !=0
      p = Integer(self.price)/Integer(self.mt)
    end
      return p
  end


end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :object, polymorphic: true
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord

  has_one :user
end

app/models/search.rb
class Search < ApplicationRecord
  
  has_many :search_results
  has_many :listings, through: :search_results
  belongs_to :user
  belongs_to :zone

end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :search
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_one :profile
         has_many :notifications
         accepts_nested_attributes_for :profile


   def displayname
     if self.profile.name != "" && self.profile.name != nil
       return self.profile.name + " " +self.profile.surname
     end

     return self.email

   end

   def notification_to_read
     self.notifications.where(seen:false)
   end

   def ispro
     if self.pro_end_date != nil
        if self.pro_end_date > Time.now
          return true
        else
          return false
        end
      else
        return false
      end
   end

end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/flow_controller.rb
class FlowController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

   def index

     render layout: 'homepage'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit

  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to edit_profile_path(@profile.id), notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :surname, :avatarimg_url, :agenzia)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
   content_for(:title) { page_title }
  end

 end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/flow_helper.rb
module FlowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper


  def parse
    logger.info("Test")
  end
end

app/helpers/my_listing_helper.rb
module MyListingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_helper.rb
module UserHelper

  def show_avatar(user)
    if user.profile.avatarimg_url != "" && user.profile.avatarimg_url !=nil 
      image_tag(user.profile.avatarimg_url, class: 'avatar-circle')
    else
      render partial: 'partials/avatar'
    end
  end


end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/profiles/_form.html.erb
<%= bootstrap_form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-12">
      <%= f.text_field :name , label:"Nome"%>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= f.text_field :surname, label:"Cognome" %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= f.text_field :agenzia ,label:"Agenzia"%>
  </div>
</div>

  <div class="footer">
    <%= f.submit "Salva", :class => "btn btn-default btn-fill submit"%>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<% title "Profile Utente" %>
<div class="container-fluid" role="main">
    <div class="row">

        <div class="col-md-6">
            <div class="card">
              <div class="header">
                <h4 class="title">Informazioni Utente</h4>
              </div>
                <div class="content">
                  <%= render 'form', profile: @profile %>
                </div>
            </div>
        </div>

        <div class="col-md-6 col-sm-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                          <h4 class="title">Piano attuale</h4>
                        </div>
                        <div class="content">
                            <% if current_user.ispro %>
                              <h3>MyAgencyCall! Pro
                                  <small>scade il
                                      <%= current_user.pro_end_date.strftime("%m/%d/%Y") %></small>
                              </h3>
                            <% else %>
                              <h3>MyAgencyCall! Free
                              </h3>
                            <% end %>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <%= render "partials/price" %>
                <% SubscriptionHelper.getplans.each do |plan| %>
                <%= render "partials/stripeplan",plan: plan %>
                <% end %>
            </div>

        </div>
    </div>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Avatarimg url</th>
      <th>Agenzia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.surname %></td>
        <td><%= profile.avatarimg_url %></td>
        <td><%= profile.agenzia %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @profile.surname %>
</p>

<p>
  <strong>Avatarimg url:</strong>
  <%= @profile.avatarimg_url %>
</p>

<p>
  <strong>Agenzia:</strong>
  <%= @profile.agenzia %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>