config/routes.rb
Rails.application.routes.draw do


  get 'flow/index'

  get 'hello_world', to: 'hello_world#index'
  resources :customers
  get 'notification/view'

  mount Crono::Web, at: '/crono'


  root "home#index"

  get 'subscription/new'

  get 'subscription/subscription_checkout'

  post 'subscription/webhook'

  get 'home/index'

  post 'subscription/subscription_checkout'
  get 'subscription/cancel_subscription'
  get 'subscription/plans'


  resources :profiles
  get 'service_test/index'

  resources :zones

  get 'my_interaction/index'
  get 'my_interaction/new'
  post 'my_interaction/create'

  resources :interactions

  devise_for :users,
               controllers: { registrations: "registrations" }

  get 'my_listing/index'

  resources :searches
  resources :listings
  get 'porta_portese/index'
  get 'porta_portese/run_search'

  get 'results' , to: 'listings#view'

namespace 'api' do
  get 'listing_for_search', to: 'listings#getListingForSearch'
  get 'togglefav', to: 'listings#togglefav'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  default_scope {where(user_id: Current.user.id)}
  belongs_to :user

end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  belongs_to :customer
  default_scope {where(user_id: Current.user.id)}
  accepts_nested_attributes_for :customer

end

app/models/listing.rb
class Listing < ApplicationRecord
  acts_as_votable
  has_many :search_results
  has_many :searches, through: :search_results
  has_many :interactions
  belongs_to :user
  belongs_to :zone

  def pricemq
    p=0
    if self.price != nil && self.mt != nil && self.price != ""  && self.mt != "" && self.mt !=0
      p = Integer(self.price)/Integer(self.mt)
    end
      return p
  end


end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :object, polymorphic: true
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord

  has_one :user
end

app/models/search.rb
class Search < ApplicationRecord
  
  has_many :search_results
  has_many :listings, through: :search_results
  belongs_to :user
  belongs_to :zone

end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :search
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_one :profile
         has_many :notifications
         accepts_nested_attributes_for :profile


   def displayname
     if self.profile.name != "" && self.profile.name != nil
       return self.profile.name + " " +self.profile.surname
     end

     return self.email

   end

   def notification_to_read
     self.notifications.where(seen:false)
   end

   def ispro
     if self.pro_end_date != nil
        if self.pro_end_date > Time.now
          return true
        else
          return false
        end
      else
        return false
      end
   end

end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/api/listings_controller.rb
class Api::ListingsController < ApplicationController
  before_action :authenticate_user!


  def getListingForSearch
    search  = Search.where(:id => params['search_id']).where(:user_id => current_user.id).first
    @listings = search.listings.order('tel DESC')
    render :template => 'listings/index.json'
  end


  def togglefav
    @listing = Listing.find(params['listing_id'])
    @listing.favourite = !@listing.favourite
    @listing.save!

    render :template => 'listings/show.json'
  end
end

app/controllers/flow_controller.rb
class FlowController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

   def index

     render layout: 'homepage'
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.where(:user_id => current_user.id)
  end


  def view
    @has_help = true



    @search = Search.find(params['search_id'])
    @min_prc = params['min_prc']
    @max_prc = params['max_prc']
    @min_mq = params['min_mq']
    @max_mq = params['max_mq']


    @results = @search.search_results.joins(:listing)
    if(@min_mq != nil && @min_mq != "")
      @results = @results.where('mt > ?',@min_mq)
    end
    if(@max_mq != nil && @max_mq != "")
      @results = @results.where('mt < ?',@max_mq)
    end
    if(@min_prc != nil && @min_prc != "")
      @results = @results.where('PRICE > ?',@min_prc)
    end
    if(@max_prc != nil && @max_prc != "")
      @results = @results.where('PRICE < ?',@max_prc)
    end

    if !current_user.ispro
      logger.info("Listing for non pro user")
      @results = @results.limit(10)
    else
      logger.info("Listing for pro user")
      @results = @results
    end



    @newcount =  @search.search_results.where(:is_new => true).count
    @avg_pricemq = @search.search_results.joins(:listing).average('price/mt')
    @title = "Annunci per " + @search.keyword + " in zona "+ @search.zone.name




    NotificationService.clear_search_notification(@search.id)

  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :link, :tel, :tel2, :email, :description, :insert_date, :mt, :zona, :id_annuncio, :origin, :price,:favourite)
    end
end

app/helpers/api/listings_helper.rb
module Api::ListingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
   content_for(:title) { page_title }
  end

 end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/flow_helper.rb
module FlowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper


  def parse
    logger.info("Test")
  end
end

app/helpers/my_listing_helper.rb
module MyListingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_helper.rb
module UserHelper

  def show_avatar(user)
    if user.profile.avatarimg_url != "" && user.profile.avatarimg_url !=nil 
      image_tag(user.profile.avatarimg_url, class: 'avatar-circle')
    else
      render partial: 'partials/avatar'
    end
  end


end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/listings/_filterform.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12 ">
      <div class="card">
          <div class="content">
          <%=  bootstrap_form_tag url: '/results', layout: :inline ,method:"get" do |f| %>
          <%= f.text_field :min_mq  , hide_label: true,placeholder: "Min. Mq" ,value: @min_mq%>
          <%= f.text_field :max_mq  , hide_label: true,placeholder: "Max. Mq" ,value: @max_mq %>
          <%= f.text_field :min_prc , hide_label: true,placeholder: "Prezzo Min." ,value: @min_prc %>
          <%= f.text_field :max_prc , hide_label: true ,placeholder: "Prezzo Max.",value: @max_prc %>
          <input type="hidden" value="<%=search_id%>" name="search_id" />
          <%= f.submit "Filtra"  %>
<a href="/results?search_id=<%=search_id %>" class="btn btn-warning"> Reset</a>
          <% end  %>
          </div>
      </div>
  </div>
</div>

app/views/listings/_form.html.erb
<%= bootstrap_form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :title %>
    <%= f.text_field :link %>
    <%= f.text_field :tel %>
    <%= f.text_field :tel2 %>
    <%= f.text_field :email %>
    <%= f.text_area :description %>
    <%= f.date_select :insert_date %>
    <%= f.number_field :mt %>
    <%= f.text_field :zona %>
    <%= f.text_field :id_annuncio %>
    <%= f.text_field :origin %>
    <%= f.text_field :price %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Tel</th>
      <th>Tel</th>
      <th>Email</th>
      <th>Descrizione</th>
      <th>Insert date</th>
      <th>Mt</th>
      <th>Zona</th>
      <th>Id annuncio</th>
      <th>Origin</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.link %></td>
        <td><%= listing.tel %></td>
        <td><%= listing.tel2 %></td>
        <td><%= listing.email %></td>
        <td><%= listing.description %></td>
        <td><%= listing.insert_date %></td>
        <td><%= listing.mt %></td>
        <td><%= listing.zone.name %></td>
        <td><%= listing.id_annuncio %></td>
        <td><%= listing.origin %></td>
        <td><%= listing.price %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<% title @listing.title %>
<div class="container-fluid" role="main">

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="header">
                    <h4 class="title">Info Contatto</h4>
                </div>
                <div class="content">
                    <table class="table table-condensed table-striped">
                        <tr>
                            <td>Link</td>
                            <td>
                                <a href="<%= @listing.link %>">Visualizza</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Telefono</td>
                            <td><%= @listing.tel %></td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td><%= @listing.email %></td>
                        </tr>
                    </table>

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="header">
                    <h4 class="title">Info Annuncio</h3>
                </div>
                <div class="content">
                    <table class="table table-condensed table-striped">
                        <tr>
                            <td>Mq</td>
                            <td><%= @listing.mt %></td>
                        </tr>
                        <tr>
                            <td>Prezzo</td>
                            <td><%= @listing.price %></td>
                        </tr>
                        <tr>
                            <td>Zona</td>
                            <td><%= @listing.zone.name  %></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Descrizione</h4>
                </div>
                <div class="content">
                    <%= @listing.description %>
                </div>

            </div>
        </div>
    </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Interazioni
                            <a href="/my_interaction/new?listing_id=<%= @listing.id %>&inttype=Tel">
                                <button class="btn btn-primary btn-wd btn-sm btn-fill">Nuova</button>
                            </a>
                        </h4>
                    </div>
                    <div class="content">
                        <table id="interaction_table" class="table table-bordered table-striped">
                            <thead>
                                <th>Id</th>
                                <th>Creata</th>
                                <th>Nome</th>
                                <th>Tipo</th>
                                <th>Voto</th>
                            </thead>
                            <tbody>
                                <% @listing.interactions.each() do | interaction | %>

                                <tr>
                                    <td>
                                        <%= interaction.id %></td>
                                    <td>
                                        <%= interaction.created_at.to_formatted_s(:long) %></td>
                                    <td>
                                        <%= interaction.name %></td>
                                    <td>
                                        <%= interaction.inttype %></td>
                                    <td>
                                        <%= interaction.vote %></td>
                                </tr>
                                <% end %>

                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
</div>

app/views/listings/view.html.erb
<div class="container-fluid">
    <% title @title %>
    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="card" data-step="1" data-intro="Annunci trovati per la ricerca.">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big icon-warning text-center">
                                <i class="fa fa-home"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Annunci</p>
                                <%= @search.listings.count %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card" data-step="2" data-intro="Il prezzo medio degli annunci estratti dalla ricerca.">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big icon-success text-center">
                                <i class="fa fa-euro"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Prezzo / Mq</p>
                                <%= number_to_currency( @avg_pricemq, unit: "", delimiter: ".",precision:0)  %>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card" data-step="3" data-intro="I nuovi annunci trovati dall' ultima ricerca.">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="icon-big icon-danger text-center">
                                <i class="fa fa-exclamation-circle"></i>
                            </div>
                        </div>
                        <div class="col-xs-7">
                            <div class="numbers">
                                <p>Nuovi
                                </p>
                                <%=  @newcount  %>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

    <% if !current_user.ispro %>
    <div class="row">
        <div class="col-md-12">
            <h3>Per vedere più annunci sottoscrivi il piano MyAgencyCall! Pro! dalla pagina del
                <%=link_to "Tuo Profilo", edit_profile_path(current_user.profile.id) %></h3>
        </div>
    </div>
    <% end %>
    <%= render 'filterform', search_id: @search.id %>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="content">
                    <!--  <listings v-bind:searchid="<%= @search.id %>"></listings> -->
                    <table id="listing_table" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>N</th>
                                <th>Titolo</th>
                                <th>Prezzo</th>
                                <th>Mq</th>
                                <th>€/Mq</th>
                                <th>Tel.</th>
                                <th>Link</th>
                                <th></th>
                            </tr>

                        </thead>
                        <tbody>
                            <% @results.each() do |s| %>
                            <tr>
                                <% if s.is_new %>
                                <td data-step="4" data-intro="Indica che un annuncio è nuovo" >
                                    <i style="color:red" class="fa fa-exclamation red" aria-hidden="true"></i>
                                </td>
                            <% else %>
                                <td >-</td>
                                <% end %>
                                <td><%= link_to s.listing.title , s.listing %></td>
                                <td><%= number_to_currency( s.listing.price , unit: "", delimiter: ".",precision:0)   %></td>
                                <td><%= s.listing.mt %></td>
                                <td><%= s.listing.pricemq %></td>
                                <td>
                                    <a href="tel:<%= s.listing.tel %>"><%= s.listing.tel %></a>
                                </td>
                                <td>
                                    <a href="<%= s.listing.link %>">Link</a>
                                </td>
                                <td data-step="5" data-intro="Usa questo pulsante per creare una nuova interazione avventuta con l' inserzionista">
                                    <a href="/my_interaction/new?listing_id=<%= s.listing.id %>&inttype=Tel">
                                        <button class="btn btn-sm btn-success"><%= s.listing.interactions.length %>
                                            <i class="fa fa-phone" aria-hidden="true"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>