config/routes.rb
Rails.application.routes.draw do


  get 'flow/index'

  get 'hello_world', to: 'hello_world#index'
  resources :customers
  get 'notification/view'

  mount Crono::Web, at: '/crono'


  root "home#index"

  get 'subscription/new'

  get 'subscription/subscription_checkout'

  post 'subscription/webhook'

  get 'home/index'

  post 'subscription/subscription_checkout'
  get 'subscription/cancel_subscription'
  get 'subscription/plans'


  resources :profiles
  get 'service_test/index'

  resources :zones

  get 'my_interaction/index'
  get 'my_interaction/new'
  post 'my_interaction/create'

  resources :interactions

  devise_for :users,
               controllers: { registrations: "registrations" }

  get 'my_listing/index'

  resources :searches
  resources :listings
  get 'porta_portese/index'
  get 'porta_portese/run_search'

  get 'results' , to: 'listings#view'

namespace 'api' do
  get 'listing_for_search', to: 'listings#getListingForSearch'
  get 'togglefav', to: 'listings#togglefav'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  default_scope {where(user_id: Current.user.id)}
  belongs_to :user

end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  belongs_to :customer
  default_scope {where(user_id: Current.user.id)}
  accepts_nested_attributes_for :customer

end

app/models/listing.rb
class Listing < ApplicationRecord
  acts_as_votable
  has_many :search_results
  has_many :searches, through: :search_results
  has_many :interactions
  belongs_to :user
  belongs_to :zone

  def pricemq
    p=0
    if self.price != nil && self.mt != nil && self.price != ""  && self.mt != "" && self.mt !=0
      p = Integer(self.price)/Integer(self.mt)
    end
      return p
  end


end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :object, polymorphic: true
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord

  has_one :user
end

app/models/search.rb
class Search < ApplicationRecord
  
  has_many :search_results
  has_many :listings, through: :search_results
  belongs_to :user
  belongs_to :zone

end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :search
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_one :profile
         has_many :notifications
         accepts_nested_attributes_for :profile


   def displayname
     if self.profile.name != "" && self.profile.name != nil
       return self.profile.name + " " +self.profile.surname
     end

     return self.email

   end

   def notification_to_read
     self.notifications.where(seen:false)
   end

   def ispro
     if self.pro_end_date != nil
        if self.pro_end_date > Time.now
          return true
        else
          return false
        end
      else
        return false
      end
   end

end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/flow_controller.rb
class FlowController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

   def index

     render layout: 'homepage'
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /searches
  # GET /searches.json
  def index
    @has_help = true
    @page_title = "Lista Ricerche"
    @searches = Search.where(:user_id => current_user.id )
    if !current_user.ispro
      flash.now[:warning] = "Attiva il piano MyAgencyCall! Pro! per creare altre ricerche!"
    end
  end
  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    if !current_user.ispro
      c  = Search.where(:user_id => current_user.id).count
      if c > 1
        flash.now[:warning] = "Attiva il piano MyAgencyCall! Pro! per creare altre ricerche!"
        redirect_to edit_profile_path(current_user.profile.id)
      end
    end
      @search = Search.new

  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)
    @search.user = current_user
    respond_to do |format|
      if @search.save
        format.html { redirect_to searches_path, notice: 'La ricerca è stata creata, premi esegui per recuperare gli annunci o aspetta qualche minuto perchè questo avvenga automaticamente.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'La ricerca è stata eliminata.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:keyword, :zona, :last_run,:zone_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
   content_for(:title) { page_title }
  end

 end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/flow_helper.rb
module FlowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper


  def parse
    logger.info("Test")
  end
end

app/helpers/my_listing_helper.rb
module MyListingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_helper.rb
module UserHelper

  def show_avatar(user)
    if user.profile.avatarimg_url != "" && user.profile.avatarimg_url !=nil 
      image_tag(user.profile.avatarimg_url, class: 'avatar-circle')
    else
      render partial: 'partials/avatar'
    end
  end


end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/searches/_form.html.erb
<%= bootstrap_form_for(search) do |f| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <%= f.text_field :keyword , label:"Parola chiave" ,placeholder:"Es.: No Agenzie" %>

      <% zones_array = Zone.all.map { |zone| [zone.name, zone.id] } %>
      <% opt = options_for_select(zones_array,@zone_id) %>
      <%= f.select :zone_id, opt, { label: "Zona :" } %>

<br>
      <%= f.submit "Crea Ricerca", class:"btn btn-success btn-fill" %>
  <% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<% title "Lista Ricerche" %>

<div class="container-fluid">
  <% if !current_user.ispro %>
     <div class="row">
       <div class="col-md-12">
         <h3>Per creare più di 2 ricerche sottoscrivi il piano MyAgencyCall! Pro! dalla pagina del <%=link_to "Tuo Profilo", edit_profile_path(current_user.profile.id) %></h3>
       </div>
     </div>
   <% end %>
   <div class="row">
     <div class="col-md-12">
       <a href="/searches/new"><button  data-step="1" data-intro="Crea una nuova ricerca..." type="button" class="btn btn-primary btn-wd btn-fill">Nuova</button></a>
     </div>
   </div>
   <br>
   <div class="row">
     <div class="col-md-12">
       <div class="card">
              <div class="content">
                <table class="table dataTable table-striped table-bordered" id="search-table">
                  <thead>
                    <tr>
                      <th>Parola Chiave</th>
                      <th>Zona</th>
                      <th>Annunci</th>
                      <th></th>

                     </tr>
                  </thead>
                  <tbody>
                    <% @searches.each do |search| %>
                      <tr>
                        <td><%= search.keyword %></td>
                        <td><%= search.zone.name %></td>
                         <td data-step="3" data-intro="Visualizza gli annunci trovati"><%= link_to search.listings.count(), results_path(:search_id => search.id) %></td>
                        <td data-step="2" data-intro="Esegui e recupera tutti gli annunci..."><%= link_to ('<i class="fa fa-cogs"></i> Esegui').html_safe, porta_portese_run_search_path(:search_id => search.id),class:"btn btn-simple btn-success btn-icon like" %>
                         <%= link_to ('<i class="fa fa-trash-o"></i>').html_safe, search, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-simple btn-danger btn-icon like"%></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
         </div>
       </div>
     </div>
  </div>
</div>

app/views/searches/new.html.erb
<% title "Nuova Ricerca" %>
<div class="container-fluid" role="main">

        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="content">
                        <%= render 'form', search: @search %>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @search.keyword %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @search.zona %>
</p>

<p>
  <strong>Last run:</strong>
  <%= @search.last_run %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>