config/routes.rb
Rails.application.routes.draw do


  get 'flow/index'

  get 'hello_world', to: 'hello_world#index'
  resources :customers
  get 'notification/view'

  mount Crono::Web, at: '/crono'


  root "home#index"

  get 'subscription/new'

  get 'subscription/subscription_checkout'

  post 'subscription/webhook'

  get 'home/index'

  post 'subscription/subscription_checkout'
  get 'subscription/cancel_subscription'
  get 'subscription/plans'


  resources :profiles
  get 'service_test/index'

  resources :zones

  get 'my_interaction/index'
  get 'my_interaction/new'
  post 'my_interaction/create'

  resources :interactions

  devise_for :users,
               controllers: { registrations: "registrations" }

  get 'my_listing/index'

  resources :searches
  resources :listings
  get 'porta_portese/index'
  get 'porta_portese/run_search'

  get 'results' , to: 'listings#view'

namespace 'api' do
  get 'listing_for_search', to: 'listings#getListingForSearch'
  get 'togglefav', to: 'listings#togglefav'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  default_scope {where(user_id: Current.user.id)}
  belongs_to :user

end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  belongs_to :customer
  default_scope {where(user_id: Current.user.id)}
  accepts_nested_attributes_for :customer

end

app/models/listing.rb
class Listing < ApplicationRecord
  acts_as_votable
  has_many :search_results
  has_many :searches, through: :search_results
  has_many :interactions
  belongs_to :user
  belongs_to :zone

  def pricemq
    p=0
    if self.price != nil && self.mt != nil && self.price != ""  && self.mt != "" && self.mt !=0
      p = Integer(self.price)/Integer(self.mt)
    end
      return p
  end


end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :object, polymorphic: true
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord

  has_one :user
end

app/models/search.rb
class Search < ApplicationRecord
  
  has_many :search_results
  has_many :listings, through: :search_results
  belongs_to :user
  belongs_to :zone

end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :search
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_one :profile
         has_many :notifications
         accepts_nested_attributes_for :profile


   def displayname
     if self.profile.name != "" && self.profile.name != nil
       return self.profile.name + " " +self.profile.surname
     end

     return self.email

   end

   def notification_to_read
     self.notifications.where(seen:false)
   end

   def ispro
     if self.pro_end_date != nil
        if self.pro_end_date > Time.now
          return true
        else
          return false
        end
      else
        return false
      end
   end

end

app/models/zone.rb
class Zone < ApplicationRecord
end

app/controllers/flow_controller.rb
class FlowController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

   def index

     render layout: 'homepage'
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:name, :pp_url_part)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
   content_for(:title) { page_title }
  end

 end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/flow_helper.rb
module FlowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper


  def parse
    logger.info("Test")
  end
end

app/helpers/my_listing_helper.rb
module MyListingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_helper.rb
module UserHelper

  def show_avatar(user)
    if user.profile.avatarimg_url != "" && user.profile.avatarimg_url !=nil 
      image_tag(user.profile.avatarimg_url, class: 'avatar-circle')
    else
      render partial: 'partials/avatar'
    end
  end


end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<%= form_for(zone) do |f| %>
  <% if zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% zone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :pp_url_part %>
    <%= f.text_field :pp_url_part %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<div class="right_col" role="main">
<h1>Editing Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>
</div>

app/views/zones/index.html.erb
<div class="right_col" role="main">
<p id="notice"><%= notice %></p>

<h1>Zones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pp url part</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zones.each do |zone| %>
      <tr>
        <td><%= zone.name %></td>
        <td><%= zone.pp_url_part %></td>
        <td><%= link_to 'Show', zone %></td>
        <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
        <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zone', new_zone_path %>
</div>

app/views/zones/new.html.erb
<div class="right_col" role="main">
<h1>New Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Back', zones_path %>

</div>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zone.name %>
</p>

<p>
  <strong>Pp url part:</strong>
  <%= @zone.pp_url_part %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>